### PR TITLE
WIP: Attempting to add block to project

### PR DESCRIPTION
**Pull request by juangrt**
@ohall and @yshen01 ,
Trying to add my npm module to the project. The npm run build is failing.

It works on my local test project that is using npm link.

Let me know if know if you see something I don't.

### CODE REVIEW

**Comment by ohall** [comment]
@juangrt the module is published on npm to a version that works with what's specified in the package.json?

**Comment by juangrt** [comment]
@ohall Not sure I understand the question. But the module works with what's in the package.json, and works in my test react component. The module that's published to npm is identical to the one that's linked locally.

**Comment by ohall** [comment]
@juangrt 

```
$ npm install
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/ohall1/.nvm/versions/node/v4.2.2/bin/node" "/Users/ohall1/.nvm/versions/node/v4.2.2/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v3.7.1
npm ERR! code E404

npm ERR! 404 Not found on remote : one-toggleBlockView
npm ERR! 404 
npm ERR! 404  'one-toggleBlockView' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of 'onesie'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ohall1/Documents/projects/onesie/npm-debug.log

```

**Comment by ohall** [comment]
@juangrt I think this is actually the name of your module:
https://github.com/juangrt/one-toggleBlockView/blob/master/package.json#L2

**Comment by ohall** [comment]
`$ npm install --save onesie-toggle-environment-block`

**Comment by ohall** [comment]
@juangrt can I see the new component in the UI if I check out this branch?

**Comment by ohall** [comment]
Looks like eslint is not working with `npm test` for some reason, but seeing this when I run it manually

```
/Users/ohall1/Documents/projects/onesie/src/app/components/scroll.jsx
   4:8   error  'ClusterToggleView' is defined but never used  no-unused-vars
   6:5   error  'mockDataThumb1' is defined but never used     no-unused-vars
   8:16  error  Strings must use singlequote                   quotes
   8:32  error  Strings must use singlequote                   quotes
   9:9   error  Strings must use singlequote                   quotes
  10:11  error  Strings must use singlequote                   quotes
  11:12  error  Strings must use singlequote                   quotes

```

**Comment by juangrt** [comment]
@ohall currently you cannot see the component if you checkout the branch. I didn't want to stuff randomly in place, so I tested it by randomly placing it somewhere and then removed it.

**Pull request merged**
