### PR TITLE
Copy to clipboard

### PR DESCRIPTION
**Pull request by yshen01**
Use react-copy-to-clipboard component to implement copying FQDNs and IPs to clipboard.
Each platform has two separate icons, one for copying FQDNs and one for copying IPs. The copied text will be new line separated list of FQDNs or IPs for that platform.

screen shot 2016-12-09 at 1 29 37 pm

### CODE REVIEW

**Comment by yshen01** [comment]
@ohall

**Comment by ohall** [comment]
@yshen01 We were having and issue with linting.  Could you merge master and make the lint fixes?  it's conflicted now, but you should be able to resolve pretty easily.  Let me know if it's a problem

**Comment by yshen01** [comment]
@ohall master merged and conflict resolved

**Comment by ohall** [comment]
@yshen01 Awesome!  Works great.  👍  merge it!

**Pull request merged**
